version: '3.7'

services:
    php:
        build: ./docker/php
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        depends_on:
          - postgres
    postgres:
        image: postgres:9.6
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=symfony
            - POSTGRES_PASSWORD=symfony
            - POSTGRES_DB=symfony